### ISSUE TITLE
Per Hour inconsitency

### ISSUE THREAD

**Issue by nazreen** [dayjobs/one-day-jobs#37]
During post job: field is called 'Salary' and next is called 'no. of hours' but on the job page, it becomes 'RMXX per hour'. 

2 choices, remove the 'per hour' or make it calculate Salary / No. of hour so the value is correct

**Comment by nazreen** [comment]
![image](https://cloud.githubusercontent.com/assets/10964594/7816594/d62b7c22-0401-11e5-8696-53484bd9c488.png)

**Comment by nxmohamad** [comment]
Ryan, on the job page this does not show up. But in the fresh_jobs module it still shows up as 'per hour'.

**Comment by nazreen** [comment]
![image](https://cloud.githubusercontent.com/assets/10964594/8024469/7699c9ca-0d67-11e5-8d79-458b61d594a1.png)
